# Browseer
windowrulev2 = workspace 2, monitor 1, class:^(zen-browser)$

#Music
windowrulev2 = workspace 5, monitor 1, class:^(spotify-player)$

#Discord 
windowrulev2 = workspace 4, monitor 1, class:^(webcord)$

