format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
$container\
$terraform\
$cmd_duration\
$line_break\
$python\
$character"""

[kubernetes]
disabled = false
symbol = "⎈"
format = '[$symbol](bright-black) [$context( \($namespace\))]($style)'

[[kubernetes.contexts]]
context_pattern = "^production$"
context_alias = "production"
style = "blue"

[container] 
format = '[$symbol \[$name\]]($style) '

[terraform]
format = '[🏎💨 $workspace]($style) '


[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"